[package]
name = "llm-rig"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
dotenv = "0.15.0"
rig-core = "0.4.1"
schemars = "0.8.21"
serde = "1.0.215"
serde_derive = "1.0.215"
serde_json = "1.0.133"
tokio = { version = "1", features = ["full"] }
